name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # Adjust Node.js version if needed

      - name: Install dependencies
        run: npm install

      - name: Build the project
        env:
          NEXT_PUBLIC_SERVICE_ID: ${{ secrets.NEXT_PUBLIC_SERVICE_ID }}
          NEXT_PUBLIC_TEMPLATE_ID: ${{ secrets.NEXT_PUBLIC_TEMPLATE_ID }}
          NEXT_PUBLIC_USER_ID: ${{ secrets.NEXT_PUBLIC_USER_ID }}
          NEXT_PUBLIC_TEMPLATE_ID_CARRIER_FORM: ${{ secrets.NEXT_PUBLIC_TEMPLATE_ID_CARRIER_FORM }}
        run: |
          npm run build
          npm run export

      - name: Add CNAME file
        run: echo "trucktalklogistics.com" > ./docs/CNAME # Replace with your custom domain

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # This is the default output directory for `next export`
